dnl -*- autoconf -*-
# Macros needed to find dune-test and dependent libraries.  They are called by
# the macros in ${top_src_dir}/dependencies.m4, which is generated by
# "dunecontrol autogen"

# Additional checks needed to build dune-test
# This macro should be invoked by every module which depends on dune-test, as
# well as by dune-test itself
AC_DEFUN([DUNE_TEST_CHECKS])

# Additional checks needed to find dune-test
# This macro should be invoked by every module which depends on dune-test, but
# not by dune-test itself
AC_DEFUN([DUNE_TEST_CHECK_MODULE],
[
  DUNE_CHECK_MODULES([dune-test])
])
